### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by michield** [lucasheld/uptime-kuma-api#12]
This is a bit of a weird one. I'm using the ansible to add a bunch of monitors with the exact same task:

```
  - name: Create monitors
    lucasheld.uptime_kuma.monitor:
      api_url: "{{ api_url }}"
      api_token: "{{ api_token }}"
      name: "{{ item }}"
      type: http
      url: "https://{{ item }}"
      state: present
    with_items: "{{ urls }}"
```

most of them are fine, but once or twice, I get the following error.

`File \"/usr/local/lib/python3.11/site-packages/uptime_kuma_api/api.py\", line 643, in edit_monitor\n    _check_arguments_monitor(data)\n  File \"/usr/local/lib/python3.11/site-packages/uptime_kuma_api/api.py\", line 243, in _check_arguments_monitor\n    _check_argument_conditions(conditions, kwargs)\n  File \"/usr/local/lib/python3.11/site-packages/uptime_kuma_api/api.py\", line 191, in _check_argument_conditions\n    if min_ is not None and value < min_:\n                            ^^^^^^^^^^^^\nTypeError: '<' not supported between instances of 'NoneType' and 'int'\n"}

Seems a bit odd that it fails on some but is fine on most.

I haven't been able to debug it more just yet.

`

By the way @lucasheld many thanks for this great tool.

**Comment by lucasheld** [comment]
I'm not sure how the problem can occur with this exact task.

The problem can occur when one of the following monitor options is `None`:
- `interval`
- `maxretries`
- `retryInterval`
- `maxredirects`
- `port`

For example:
```yml
- name: Create monitors
  lucasheld.uptime_kuma.monitor:
    api_url:"{{ api_url }}"
    api_token: "{{ api_token }}"
    name: "{{ item }}"
    type: http
    url: "https://{ item }}"
    port: None
    state: present
  with_items: "{{ urls }}"
```
